#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { highlight, loadPackage } = require(path.join(__dirname, "runtime-js", "highlight.js"));

const [treePath, packagePath, extra] = process.argv.slice(2);
if (!treePath || !packagePath || extra) {
  console.error("usage: hl-js <tree.json> <package.highlight.json>");
  process.exit(1);
}

try {
  const tree = JSON.parse(fs.readFileSync(treePath, "utf8"));
  const rawPackage = JSON.parse(fs.readFileSync(packagePath, "utf8"));
  process.stdout.write(`${JSON.stringify(highlight(tree, loadPackage(rawPackage)))}\n`);
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
