fruit.apple.color = "red"
fruit.apple.taste = "sweet"
fruit.banana.color = "yellow"

[fruit.apple.origin]
country = "Kazakhstan"
region = "Almaty"

[[fruit.banana.varieties]]
name = "cavendish"

[[fruit.banana.varieties]]
name = "plantain"
