#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Fetch every pinned grammar's C sources, and say what shape each one is in.

    ./harness/ts_grammars.py [--survey] [--language NAME] [--json] [--refresh]

Route C3 transcodes `parser.c`, so the parse layer needs the *source* of every
grammar the corpus pins -- not the compiled module `tree-sitter` imports. Until
now those sources were fetched by hand into a session scratchpad, which meant
the path from "pinned version" to "blob" existed only in a transcript. This is
that path, written down.

The pins are not restated here. They come from `harness/languages/*.toml`, the
same `grammar` field `manifest.py` installs from, so a grammar cannot be
transcoded at one version and parsed at another.

## The sdist is the source, and three of them are incomplete

The sdist is what PyPI built the wheel from, and the wheel is what generated
`corpus/trees/`. So the sdist's `parser.c` is the grammar the oracle actually
speaks, and it is what gets transcoded.

**Three sdists are missing their scanner.** `tree-sitter-css` 0.25.0,
`tree-sitter-python` 0.25.0 and `tree-sitter-yaml` 0.7.2 declare external
tokens -- 3, 12 and 113 of them -- and ship no `src/scanner.c`. Their
`setup.py` globs `src/*.c`, so those sdists cannot build the module they
describe; nobody notices, because everyone installs the wheel. Transcoding one
of those trees yields a blob with no scanner, which cannot parse. Every other
pinned grammar ships its scanner, including the multi-grammar ones -- xml's
sdist carries both `xml/src/scanner.c` and `dtd/src/scanner.c`.

For those three only, the upstream repository at the pinned tag is cloned and
its `scanner.c` copied in. That checkout is trusted only after its `parser.c`
is shown to match the sdist's, which is what establishes that the tag holds the
same grammar the scanner belongs to. Measured on css: identical, byte for byte.

**The comparison tolerates two regions, and only two.** A repository tag can be
cut before a version bump reaches the generated file, so `tree-sitter-rust`
v0.24.0's `parser.c` differs from the 0.24.0 sdist's in exactly the
`/* Automatically generated by ... */ ` banner and the `.minor_version` /
`.patch_version` fields of the language `metadata` struct -- 6 lines out of
204,330, with every table identical. `ts_transcode.py` deliberately does not
transcode `metadata`, so neither region can reach a blob. Any other difference
is a hard failure.

The upstream URL is not guessed -- it is read out of the sdist's own
`PKG-INFO`. It can still be stale: xml's names `tree-sitter/tree-sitter-xml`,
which no longer carries the tags, while the grammar lives under
`tree-sitter-grammars/`. That costs nothing here because xml's sdist is
complete, but it is why the git path is a fallback rather than the rule.

## What the survey reports

`--survey` reports the three facts that decide how much work each language is:

* **parser.c size** -- the table volume, which drives the blob's size and
  roughly the transcode time. It spans three orders of magnitude here, from
  json's 27 KB to kotlin's 22 MB.
* **ABI version** -- 13, 14 and 15 lay out `TSLanguage` differently; the
  transcoder reads the struct, so an unhandled ABI is a hard stop.
* **external tokens** -- read from `parser.c`'s own `EXTERNAL_TOKEN_COUNT`,
  never from whether a `scanner.c` file happens to be present, which is the
  mistake the sdists invite. A grammar with external tokens needs its scanner
  compiled to scanner-VM bytecode (`docs/scanner-vm.md`) and attached to the
  blob with `ts_transcode.py --scanner`.

Sources land in `.grammars/<language>/`, which is gitignored: they are a
reproducible download, not an artifact.

## Multi-grammar repositories

typescript, markdown and xml each ship several grammars in one repository
(`typescript`/`tsx`, block/inline, `xml`/`dtd`). The manifest's
`grammar_symbol` says which one the corpus uses -- `language_typescript`,
`language_xml`, plain `language` for markdown's block grammar -- and only that
one is marked required. The others are reported, because a grammar we do not
need today is still a grammar someone will ask about.
"""

import argparse
import io
import json
import re
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import manifest as mf  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".grammars"

PIN = re.compile(r"^([A-Za-z0-9._-]+)==([A-Za-z0-9._-]+)$")
GIT = re.compile(r"^([A-Za-z0-9._-]+)\s*@\s*git\+(\S+?)@(\S+)$")
ABI = re.compile(r"#define\s+LANGUAGE_VERSION\s+(\d+)")
EXTERNALS = re.compile(r"#define\s+EXTERNAL_TOKEN_COUNT\s+(\d+)")
PROJECT_URL = re.compile(r"^Project-URL:\s*([^,]+),\s*(\S+)", re.M)
HOME_PAGE = re.compile(r"^Home-page:\s*(\S+)", re.M)
# Metadata 2.1 replaced `Home-page` with labelled `Project-URL` entries, and
# grammars use several labels for the same repository. Most useful first.
REPO_LABELS = ("source code", "source", "repository", "homepage")


class GrammarError(Exception):
    """A grammar could not be fetched, or its two sources disagree."""


# --------------------------------------------------------------------------
# fetching


def pin_of(spec: str) -> tuple[str, str, str]:
    """`(kind, a, b)` for a manifest `grammar` field: pypi name/version, or git url/ref."""
    if m := PIN.match(spec.strip()):
        return ("pypi", m.group(1), m.group(2))
    if m := GIT.match(spec.strip()):
        return ("git", m.group(2), m.group(3))
    raise GrammarError(f"cannot read grammar pin {spec!r}")


def fetch_sdist(name: str, version: str, dest: Path) -> None:
    """Unpack the sdist, stripping its single top-level directory."""
    meta = json.load(
        urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json")
    )
    urls = meta["urls"]
    sdist = next((u for u in urls if u["packagetype"] == "sdist"), None)
    if sdist is None:
        kinds = ", ".join(sorted({u["packagetype"] for u in urls})) or "nothing"
        raise GrammarError(f"{name}=={version} publishes {kinds}, no sdist")
    raw = urllib.request.urlopen(sdist["url"]).read()
    opener = (
        zipfile.ZipFile(io.BytesIO(raw))
        if sdist["url"].endswith(".zip")
        else tarfile.open(fileobj=io.BytesIO(raw))
    )
    with opener as archive:
        archive.extractall(dest, **({"filter": "data"} if _tar_filter(archive) else {}))
    unwrap(dest)


def _tar_filter(archive) -> bool:
    """Python 3.12+ wants an extraction filter; zipfile has no such argument."""
    return isinstance(archive, tarfile.TarFile)


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, capture_output=True)


def fetch_git(url: str, ref: str, dest: Path) -> None:
    """Shallow-clone at the pinned tag, trying the two tag conventions in use.

    Most grammars tag `v0.25.0`; `tree-sitter-kotlin` tags a bare `1.1.0`. Try
    the version verbatim first, since a manifest pinned directly to git already
    carries the exact ref.
    """
    attempts = [ref] if ref.startswith("v") else [f"v{ref}", ref]
    for tag in attempts:
        try:
            git("clone", "--quiet", "--depth", "1", "--branch", tag, url, str(dest))
            return
        except subprocess.CalledProcessError:
            shutil.rmtree(dest, ignore_errors=True)
    raise GrammarError(f"no tag {' or '.join(attempts)} in {url}")


def repo_url(sdist: Path) -> str:
    """The upstream repository, out of the sdist's own metadata rather than a guess."""
    info = sdist / "PKG-INFO"
    if not info.is_file():
        raise GrammarError(f"{sdist.name}: sdist has no PKG-INFO to read a repo URL from")
    text = info.read_text(encoding="utf-8", errors="replace")
    labelled = {
        label.strip().lower(): url for label, url in PROJECT_URL.findall(text)
    }
    for label in REPO_LABELS:
        if label in labelled:
            return labelled[label]
    if m := HOME_PAGE.search(text):
        return m.group(1)
    raise GrammarError(f"{sdist.name}: no repository URL in PKG-INFO")


def unwrap(dest: Path) -> None:
    """Hoist a lone top-level directory, so every language has the same shape."""
    entries = [p for p in dest.iterdir() if p.name != ".git"]
    if len(entries) == 1 and entries[0].is_dir():
        inner = entries[0]
        for child in list(inner.iterdir()):
            child.rename(dest / child.name)
        inner.rmdir()


BANNER = re.compile(rb"^/\* Automatically generated by tree-sitter[^\n]*\n")
VERSION_FIELD = re.compile(rb"^\s*\.(?:minor|patch)_version = \d+,\n", re.M)


def tables_of(parser_c: Path) -> bytes:
    """`parser.c` with the two regions a tag/sdist skew can legitimately move.

    The generator banner carries a commit hash, and `.minor_version` /
    `.patch_version` sit in the language `metadata` struct, which
    `ts_transcode.py` deliberately does not transcode. Nothing else in the file
    is allowed to differ -- everything else is a table.
    """
    raw = parser_c.read_bytes()
    return VERSION_FIELD.sub(b"", BANNER.sub(b"", raw, count=1))


def missing_scanners(root: Path) -> list[Path]:
    """Each grammar `src/` that declares external tokens and has no scanner."""
    absent = []
    for parser in parsers_in(root):
        src = parser.parent
        declared = EXTERNALS.search(parser.read_text(encoding="utf-8", errors="replace"))
        if declared is None or int(declared.group(1)) == 0:
            continue
        if not any((src / f"scanner{ext}").is_file() for ext in (".c", ".cc")):
            absent.append(src)
    return absent


def graft_scanners(name: str, version: str, sdist: Path, absent: list[Path]) -> str:
    """Copy the missing `scanner.c`s in from the upstream tag, once it is trusted."""
    checkout = CACHE / ".git" / name
    shutil.rmtree(checkout, ignore_errors=True)
    checkout.parent.mkdir(parents=True, exist_ok=True)
    try:
        fetch_git(repo_url(sdist), version, checkout)
        for theirs in parsers_in(sdist):
            ours = checkout / theirs.relative_to(sdist)
            if not ours.is_file():
                raise GrammarError(f"{theirs.relative_to(sdist)} absent from the checkout")
            if tables_of(ours) != tables_of(theirs):
                raise GrammarError(
                    f"{theirs.relative_to(sdist)} differs from the sdist's outside "
                    "the generator banner and metadata version"
                )
        grafted = []
        for src in absent:
            found = [
                p for ext in (".c", ".cc")
                if (p := checkout / src.relative_to(sdist) / f"scanner{ext}").is_file()
            ]
            if not found:
                raise GrammarError(
                    f"{src.relative_to(sdist)}: declares external tokens and neither "
                    "the sdist nor the tag has a scanner"
                )
            shutil.copy2(found[0], src / found[0].name)
            grafted.append(str(src.relative_to(sdist) / found[0].name))
        return "; scanner grafted from the tag: " + ", ".join(grafted)
    finally:
        shutil.rmtree(checkout, ignore_errors=True)


def fetch(name: str, spec: str, refresh: bool = False) -> Path:
    """The sources for `name`, downloading and completing them if absent."""
    dest = CACHE / name
    stamp = dest / ".verified"
    if refresh:
        shutil.rmtree(dest, ignore_errors=True)
    if stamp.is_file():
        return dest

    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True)
    try:
        kind, a, b = pin_of(spec)
        if kind == "git":
            shutil.rmtree(dest)
            fetch_git(a, b, dest)
            note = f"pinned directly to git at {b}"
        else:
            fetch_sdist(a, b, dest)
            note = f"{a}=={b} sdist"
            if absent := missing_scanners(dest):
                note += graft_scanners(name, b, dest, absent)
        stamp.write_text(note + "\n", encoding="utf-8")
    except BaseException:
        # A half-unpacked directory would be treated as a cache hit next run.
        shutil.rmtree(dest, ignore_errors=True)
        raise
    return dest


# --------------------------------------------------------------------------
# surveying


def parsers_in(root: Path) -> list[Path]:
    """Every `src/parser.c`. Multi-grammar repos have several."""
    return sorted(p for p in root.rglob("src/parser.c") if ".git" not in p.parts)


def wanted(symbol: str, grammars: list[str]) -> str | None:
    """Which of a repository's grammars the manifest's `grammar_symbol` names.

    `language_typescript` names `typescript`; a plain `language` names the one
    unsuffixed grammar, which for markdown is the block grammar and not
    `tree-sitter-markdown-inline`.
    """
    if len(grammars) == 1:
        return grammars[0]
    if suffix := symbol.removeprefix("language").lstrip("_"):
        matches = [g for g in grammars if g.split("-")[-1] == suffix]
        return matches[0] if len(matches) == 1 else None
    return min(grammars, key=len)


def survey_one(name: str, m, root: Path) -> list[dict]:
    found = parsers_in(root)
    if not found:
        return [{"language": name, "grammar": None, "required": True, "parser_c": None,
                 "abi": None, "externals": None, "scanner": None}]

    names = [str(p.parent.parent.relative_to(root)) or "." for p in found]
    required = wanted(m.grammar_symbol, names)
    rows = []
    for parser, grammar in zip(found, names):
        text = parser.read_text(encoding="utf-8", errors="replace")
        abi, ext = ABI.search(text), EXTERNALS.search(text)
        scanner = next(
            (p.name for p in sorted(parser.parent.iterdir())
             if p.stem == "scanner" and p.suffix in {".c", ".cc"}),
            None,
        )
        rows.append({
            "language": name,
            "grammar": grammar,
            "required": grammar == required,
            "parser_c": parser.stat().st_size,
            "abi": int(abi.group(1)) if abi else None,
            "externals": int(ext.group(1)) if ext else 0,
            "scanner": scanner,
        })
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--language", help="fetch/survey only this language")
    ap.add_argument("--survey", action="store_true", help="report, do not just fetch")
    ap.add_argument("--refresh", action="store_true", help="re-download even if cached")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    manifests = mf.selected(mf.load_all(), args.language)
    rows, failures = [], []
    for name, m in sorted(manifests.items()):
        try:
            rows.extend(survey_one(name, m, fetch(name, m.grammar, args.refresh)))
        except (GrammarError, subprocess.CalledProcessError) as e:
            failures.append(f"{name}: {e}")

    if args.json:
        print(json.dumps({"grammars": rows, "failures": failures}, indent=1))
        return 1 if failures else 0

    if args.survey:
        print(f"{'language':<12} {'grammar':<28} {'parser.c':>10} {'abi':>4} "
              f"{'ext':>4}  scanner")
        for r in rows:
            size = f"{r['parser_c']:,}" if r["parser_c"] else "MISSING"
            mark = " " if r["required"] else "-"
            print(f"{mark}{r['language']:<11} {(r['grammar'] or '-'):<28} {size:>10} "
                  f"{(r['abi'] or '-'):>4} {r['externals']:>4}  {r['scanner'] or ''}")
        need = [r for r in rows if r["required"]]
        scanners = sum(1 for r in need if r["externals"])
        print(f"\n{len(need)} required grammars ({len(rows)} present), "
              f"{scanners} with an external scanner. Rows marked `-` are not used "
              f"by the corpus.")
    else:
        print(f"{len(manifests) - len(failures)} grammars in {CACHE.relative_to(ROOT)}")

    for f in failures:
        print(f"  {f}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
