#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["tree-sitter"]
# ///
"""Generate everything `web/` needs that is not hand-written.

    ./web/gen.py [--language NAME] [--skip-blobs]

The apps under `web/` are static: no server, no build step, no framework. That
is only possible because this script pre-computes the two things a browser
cannot cheaply derive -- the divergence set, which needs both formatters and
the reference outputs, and the transcoded parse tables.

Everything it writes lands in `web/data/` and `web/vendor/`, both gitignored.
Nothing here is edited by hand, and nothing hand-written lives in those two
directories, so `rm -rf` on either is always safe.

Why the blobs are not committed: the sixteen total 22.9 MB raw (kotlin alone
is 7.3 MB). Gzipped they are 1.4 MB, and a page loads exactly one, so the
worst single load is kotlin at 339 KB -- an ordinary bundle. Size is a
distribution problem, not a runtime one, so it is solved by regenerating
rather than by committing.

The parse layer is copied rather than imported out of `../../harness/`, so
`web/` is a directory a static host can serve by itself.

`runtime-js/bundle.js` is CommonJS and the browser needs ESM, so it is
re-emitted as `web/vendor/runtime.mjs` with its `module.exports` line replaced.
That is the whole transformation: same bytes otherwise, so the browser runs the
same formatter the scorer does rather than a port of it.
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "harness"))
import manifest as mf  # noqa: E402
import review_formatter  # noqa: E402
import review_ledger  # noqa: E402
import score  # noqa: E402
import ts_grammars as tg  # noqa: E402
import ts_scanner_record as rec  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
DATA = WEB / "data"
VENDOR = WEB / "vendor"
VICI = Path.home() / "w" / "vici" / "js" / "src"

# The line-comment marker each language continues on `<CR>` and `o`.
#
# This is app configuration, not package data, and the distinction is real: a
# package's `comments` key lists *node types* (`line_comment`, `comment`), which
# is what the formatter needs to find comments in a tree, and says nothing about
# what a comment is spelled as. Autocomment needs the spelling, and needs it
# before a parse -- the whole point is to react to <CR> without re-parsing.
#
# A language absent from this table simply has no comment continuation.
LINE_COMMENT = {
    "css": None,          # /* */ only
    "go": "//",
    "haskell": "--",
    "html": None,         # <!-- --> only
    "javascript": "//",
    "json": None,         # no comments
    "kotlin": "//",
    "markdown": None,
    "python": "#",
    "ruby": "#",
    "rust": "//",
    "scheme": ";",
    "toml": "#",
    "typescript": "//",
    "xml": None,          # <!-- --> only
    "yaml": "#",
}


# The parse layer, already ESM and already free of node imports. Copied rather
# than imported across `../../harness/` so that `web/` is a directory a static
# host can serve on its own -- which is the whole content of Q1's answer.
PARSE_LAYER = ("ts_lr.mjs", "ts_doc.mjs", "ts_scanner_vm.mjs", "ts_scanner_pack.mjs")


def vendor() -> None:
    """Copy vici and the parse layer, and re-export the CommonJS formatter as ESM."""
    VENDOR.mkdir(parents=True, exist_ok=True)
    for name in PARSE_LAYER:
        shutil.copy(ROOT / "harness" / name, VENDOR / name)

    target = VENDOR / "vici"
    if target.exists():
        shutil.rmtree(target)
    if not VICI.is_dir():
        sys.exit(f"vici sources not found at {VICI}; clone dbalmain/vici next to this repo")
    shutil.copytree(VICI, target)

    bundle = (ROOT / "runtime-js" / "bundle.js").read_text(encoding="utf-8")
    marker = "module.exports = { format, Refusal };"
    if marker not in bundle:
        sys.exit(f"runtime-js/bundle.js no longer ends with {marker!r}; fix web/gen.py")
    esm = bundle.replace(marker, "export { format, Refusal };")
    (VENDOR / "runtime.mjs").write_text(
        "// GENERATED by web/gen.py from runtime-js/bundle.js -- do not edit.\n"
        "// The only change is the last line: CommonJS exports become ESM ones,\n"
        "// so the browser runs the same formatter the scorer does.\n" + esm,
        encoding="utf-8",
    )


def blobs(manifests: dict[str, mf.Manifest]) -> set[str]:
    """Transcode each grammar to `web/data/blobs/<lang>.blob.json`. Returns the names done."""
    out = DATA / "blobs"
    out.mkdir(parents=True, exist_ok=True)
    done = set()
    for name, m in sorted(manifests.items()):
        src = rec.grammar_src(name, m)
        cmd = [str(ROOT / "harness" / "ts_transcode.py"), str(src / "parser.c"),
               "-o", str(out / f"{name}.blob.json")]
        scanner = ROOT / "harness" / "scanners" / f"{name}.svm"
        if tg.scanner_of(src) is not None:
            if not scanner.is_file():
                print(f"  {name:<12} SKIP -- external scanner with no {scanner.name}", file=sys.stderr)
                continue
            cmd += ["--scanner", str(scanner)]
        p = subprocess.run(cmd, capture_output=True, text=True)
        if p.returncode != 0:
            print(f"  {name:<12} FAIL {(p.stdout + p.stderr).strip()[:200]}", file=sys.stderr)
            continue
        size = (out / f"{name}.blob.json").stat().st_size
        print(f"  {name:<12} {size / 1024:8.0f} KiB")
        done.add(name)
    return done


def cases(submission: Path, manifests: dict[str, mf.Manifest]) -> dict[str, list[dict]]:
    """Every current divergence, with both texts, its diff and its ledger verdict."""
    records, problems = review_formatter.divergences(submission, score.corpus(manifests))
    for problem in problems:
        print(f"  ! {problem}", file=sys.stderr)
    ledgers: dict[str, dict[str, review_ledger.Review]] = {}
    by_language: dict[str, list[dict]] = {name: [] for name in manifests}
    for record in records:
        if record.language not in ledgers:
            ledgers[record.language] = review_ledger.load("formatter", record.language)
        review = ledgers[record.language].get(record.id)
        # A file the manifest calls incomparable is outside the scorer's
        # denominator entirely -- the reference rewrites it in a way gate 3
        # cannot express as equivalent -- so it has no ledger entry and never
        # will. Counting it as "unreviewed" would invent review debt that
        # nobody can discharge; it gets its own state and its own reason.
        # Note the unit: `score.py` counts excluded *files* (12), this counts
        # excluded *cases* (file x width, 20 of which also diverge). Same set,
        # different denominator, and the two numbers are meant to differ.
        excuse = manifests[record.language].incomparable.get(record.file)
        state = "excluded" if excuse else review_ledger.state(record.hash, review)
        source = ROOT / "corpus" / "src" / record.language / record.file
        by_language[record.language].append(
            {
                "id": record.id,
                "file": record.file,
                "width": record.width,
                "hash": record.hash,
                "source": source.read_text(encoding="utf-8"),
                "ours": record.our_output,
                "reference": record.reference_output,
                "diff": record.unified_diff,
                "state": state,
                "excluded": excuse,
                "review": None if review is None else {
                    "verdict": review.verdict,
                    "reason": review.reason,
                    "reviewed_by": review.reviewed_by,
                    "reviewed_at": review.reviewed_at,
                },
            }
        )
    return by_language


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--language", help="only this language (blobs and divergences)")
    ap.add_argument("--skip-blobs", action="store_true", help="reuse whatever is already in web/data/blobs")
    args = ap.parse_args()

    known = mf.bootstrap()
    selected = mf.selected(known, args.language)
    DATA.mkdir(parents=True, exist_ok=True)

    print("vendor")
    vendor()

    if args.skip_blobs:
        have = {p.name.removesuffix(".blob.json") for p in (DATA / "blobs").glob("*.blob.json")}
        print(f"blobs        reusing {len(have)}")
    else:
        print("blobs")
        have = blobs(selected)

    print("packages")
    packages = DATA / "packages"
    packages.mkdir(exist_ok=True)
    shipped = set()
    for path in sorted((ROOT / "packages").glob("*.json")):
        if path.name.endswith(".highlight.json"):
            continue
        shutil.copy(path, packages / path.name)
        shipped.add(path.stem)

    print("divergences")
    by_language = cases(ROOT, selected)
    divergences = DATA / "divergences"
    divergences.mkdir(exist_ok=True)
    for name, items in sorted(by_language.items()):
        items.sort(key=lambda c: (c["file"], c["width"]))
        (divergences / f"{name}.json").write_text(
            json.dumps(items, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(f"  {name:<12} {len(items):3d}")

    index = []
    for name, m in sorted(selected.items()):
        items = by_language[name]
        files = sorted(p.name for p in (ROOT / "corpus" / "src" / name).iterdir() if p.suffix)
        index.append(
            {
                "name": name,
                "extensions": list(m.extensions),
                "widths": list(m.widths),
                "reference": m.reference_version,
                "files": len(files),
                "cases": len(files) * len(m.widths),
                "divergences": len(items),
                "accepted": sum(1 for c in items if c["state"] == "accepted"),
                "excluded": sum(1 for c in items if c["state"] == "excluded"),
                "needsReview": sum(1 for c in items if c["state"] not in ("accepted", "excluded")),
                "indent": json.loads((packages / f"{name}.json").read_text())["indent"]
                if name in shipped else None,
                "lineComment": LINE_COMMENT.get(name),
                "hasPackage": name in shipped,
                "hasBlob": name in have,
            }
        )
    (DATA / "languages.json").write_text(
        json.dumps(index, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    total = sum(entry["divergences"] for entry in index)
    print(f"\n{len(index)} languages, {total} divergences")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
